### PR TITLE
Adds documentation for yarn policies

### PR DESCRIPTION
**Pull request by arcanis**
The following PR adds documentation for `yarn policies set-version` (https://github.com/yarnpkg/yarn/commit/158da6c6287cbc4fee900e3704f140c3391dc28d)

### CODE REVIEW

**Comment by Haroenv** [comment]
Cool! Has this been released?

**Comment by arcanis** [comment]
@Haroenv Yep, in the 1.13! https://github.com/yarnpkg/yarn/releases/tag/v1.13.0

Will post on the Twitter account once the msi build is released

**Comment by arcanis** [comment]
Any idea what I did to broke the website? 🤔 

```
5:05:45 PM: failed during stage 'deploying site': Failed to execute deploy: context deadline exceeded
```

**Comment by arcanis** [comment]
Url: https://deploy-preview-895--yarnpkg.netlify.com/en/docs/cli/policies

**Comment by Haroenv** [comment]
looks like it works 🙌

**Comment by arcanis** [comment]
@Haroenv the site doesn't look updated 😢

**Comment by Haroenv** [comment]
triggered a new build, it looks like it was stuck on "processing" @arcanis

**Pull request merged**
