### PR TITLE
Rename ls to list in `yarn global` command

### PR DESCRIPTION
**Pull request by kaylieEB**
To be merged with next release ^26.0.0

### CODE REVIEW

**Comment by Haroenv** [comment]
What's the pr for this in yarn? I thought it was still yarn global is

**Comment by kaylieEB** [comment]
https://github.com/yarnpkg/yarn/commit/4a37df0a72922ac584bc84aaa8b8a077ce9d07ef

**Comment by Haroenv** [comment]
Nice, let's merge it when it's in a release, thank you

**Comment by kaylieEB** [comment]
awesome, thanks!

**Comment by kaylieEB** [comment]
can we merge this now?

**Comment by Haroenv** [comment]
Yep, thanks for writing this 🎉

**Pull request merged**
