### PR TITLE
chore(deps): update all deps 2017-06-30

### PR DESCRIPTION
**Pull request by Haroenv**
will probably fix #454

### CODE REVIEW

**Comment by Daniel15** [comment]
🤞

**Comment by Haroenv** [comment]
waiting for the deploy preview at http://deploy-preview-556--yarnpkg.netlify.com/en/package/whatever

**Comment by Daniel15** [comment]
I merged it since it seems safe... What's the worst that could happen? 😛

**Comment by Haroenv** [comment]
ah or merging immediately will also work 😂

**Comment by Haroenv** [comment]
It were all patches, so probably good

**Comment by Haroenv** [comment]
Whoops, can’t delete the branch while netlify is busy building... The production deploy and PR deploy are both building now.

**Pull request merged**
