### PR TITLE
chore: Remove obsolete index.html

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Removes the obsolete index redirect file after #812.

**Test plan**

Visit the main page with an unsupported languages set and makes sure it falls back to the English version.

### CODE REVIEW

**Comment by BYK** [comment]
Just verified that this works as expected now, Should be good to merge.

**Comment by Daniel15** [comment]
I think this was needed for dev, as the Netlify redirects don't work in dev
mode. Please test on your computer and ensure dev mode is OK.

**Comment by BYK** [comment]
@Daniel15 is right, abandoning.

**Comment by Daniel15** [comment]
Maybe we could add a comment to the file explaining why it's needed?

**Pull request closed without merging**
