### PR TITLE
docs(add): Add documentation for ignore-workspace-root-check

### LINKED ISSUE #681: Docs: --ignore-workspace-root-check is not documented
Moved from https://github.com/yarnpkg/yarn/issues/4711 - original issue by @customcommander

Hi,

I'm using `1.2.1` and I have the workspace feature flag enabled.

I'd like to install `lerna` as a "root" dependency:

```
yarn add lerna --dev
yarn add v1.2.1
error Running this command will add the dependency to the workspace root rather than workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
The error message is probably enough to be honest. The problem imho is that the info message suggests you can get more info at the doc page which isn't the case.

### PR DESCRIPTION
**Pull request by theSmaw**
Closes #681

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit b45f4ceaca6a7b43f189e39a1eb940bed0eb775a

https://deploy-preview-826--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
@byk, wdyt?

**Comment by BYK** [comment]
LGTM. Heads up @arcanis.

**Comment by theSmaw** [comment]
Thanks!

**Pull request merged**
