### PR TITLE
Fix CDN links for packages with long names

### PR DESCRIPTION
**Pull request by MartinKolarik**
Adds some CSS to make this look better: https://yarnpkg.com/en/package/ractive-component-loader

### CODE REVIEW

**Comment by Haroenv** [comment]
Looks okay, waiting for the preview. Thanks!

**Comment by MartinKolarik** [comment]
Preview: https://deploy-preview-730--yarnpkg.netlify.com/en/package/ractive-component-loader

**Comment by Haroenv** [comment]
looks okay, since people know that part already

**Comment by Haroenv** [comment]
sorry for not answering earlier, forgot about this PR

**Pull request merged**
