### PR TITLE
Add NPM version of yarn upgrade

### PR DESCRIPTION
**Pull request by nmn**
This is counter-intuitive, but it works AFAIK.

### CODE REVIEW

**Comment by cpojer** [comment]
Actually I think the table is wrong. `yarn upgrade` doesn't take arguments. `yarn upgrade` updates all packages to the latest version according to their semver range. The equivalent to that in npm is `rm -rf node_modules; npm install`. Would you mind updating the PR?

**Comment by nmn** [comment]
@cpojer I read the documentation, and `yarn upgrade` seems counter-intuitive. It is not used to update dependencies to new versions at all. (I just tried locally)

**Comment by cpojer** [comment]
Yarn upgrade updates dependencies to the latest version based on the semver range, not new versions.

If you have `"jest": "^16.0.0"` in your `package.json` and yarn installs 16.0.0 but 16.1.0 or 16.2.3 comes out, `yarn upgrade` will update to the newer versions. If you have `"jest": "16.0.0"` and a new version of Jest comes out, `yarn upgrade` will stick to 16.0.0.

**Comment by nmn** [comment]
@cpojer Yeah, I didn't say it right. I was trying to use yarn upgrade to change the versions in package.json.

Anyway, fixed in the new commit.

**Pull request merged**
