### PR TITLE
Translated to Japanese for peoples from Japan.

### PR DESCRIPTION
**Pull request by codemonster-lab**
Japan loves your site.
性交オフ

### CODE REVIEW

**Review by Haroenv — COMMENTED** [review]
This makes sense, thanks for your pull request. Could you move the readme to `README.ja.md` and leave the English readme as-is (with an added link to the Japanese version)? That way people can read both versions :)

**Comment by codemonster-lab** [comment]
Ok

**Comment by codemonster-lab** [comment]
I am new to Github, can u plz tell me how to do it.

**Comment by codemonster-lab** [comment]
I have done the following changes. If you have not received it, plz let me
know.☺

**Review by Haroenv — APPROVED** [review]

**Comment by Haroenv** [comment]
Thank you codemonster-san!

**Pull request merged**
