### PR TITLE
Add path setup to installation documentation

### PR DESCRIPTION
**Pull request by jdlehman**
This adds documentation on setting up the path environment variable to provide global access to yarn's bin folder.

### CODE REVIEW

**Comment by jdlehman** [comment]
The Windows section definitely needs some eyes on it. I am not familiar enough with development on a Windows machine.

**Comment by cpojer** [comment]
would you mind rebasing this?

**Comment by jdlehman** [comment]
Not at all!

**Comment by cpojer** [comment]
thank you!

**Comment by Daniel15** [comment]
Both the installer and the Chocolatey package automatically configure the path for you, so you should never have to manually configure it on Windows. I think we should remove this from the Windows tab and just keep it on the "alternatives". Similarly, on Linux, the Yarn executable is installed to `/usr/bin` so it's already on the path.

The only time you need to manually configure the path is if you manually install from a tarball.

**Comment by Daniel15** [comment]
What does this mean by "Yarn's binaries"? Does it mean executables for things you install globally through Yarn itself? 

For Windows, we should make the installer do that automatically, and remove that line from the installation page (as it's confusing) 😄

**Pull request merged**
