### PR TITLE
Update install.sh to check for proper GPG subkey

### LINKED ISSUE #761: Install script should check for expected GPG subkeys
See https://github.com/yarnpkg/yarn/issues/5223

Currently it just checks for the main GPG key, but that doesn't handle if we've recently rotated the subkeys. It should check that the proper subkey is present, too.

### PR DESCRIPTION
**Pull request by Daniel15**
Closes #761

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit 523038f88ecceadd7a55dc545c057900840352ee

https://deploy-preview-789--yarnpkg.netlify.com

**Comment by Daniel15** [comment]
Confirmed working with:
```
curl -o- -L https://deploy-preview-789--yarnpkg.netlify.com/install.sh | bash
```

**Comment by bonrails** [comment]
We started  seeing the same issue( error ) today for our PRs. 
```
gpg: BAD signature from "Yarn Packaging <yarn@dan.cx>" [unknown]
> GPG signature for this Yarn release is invalid! This is BAD and may mean the release has been tampered with. It is strongly recommended that you report this to the Yarn developers.
The command "curl -o- -L https://yarnpkg.com/install.sh | bash" failed and exited with 1 during .

```

It says `Signature made Wed 16 Mar 2022 06:39:25 PM UTC`. So probably new GPG key is available, but install script is not using the latest GPG key, hence seeing the issue?

Tried adding `- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --import` command to out travis.yml , before the `curl -o- -L https://yarnpkg.com/install.sh | bash`. But that didn't seem to work.

**Comment by Daniel15** [comment]
Hmm... The key is valid until 2023 so it shouldn't be new. It succesfully verifies locally:

```
% gpg --verify yarn-v1.22.18.tar.gz.asc
gpg: assuming signed data in 'yarn-v1.22.18.tar.gz'
gpg: Signature made Wed 16 Mar 2022 11:39:25 AM PDT
gpg:                using RSA key 6D98490C6F1ACDDD448E45954F77679369475BAA
gpg: Good signature from "Yarn Packaging <yarn@dan.cx>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
     Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
```

**Comment by Daniel15** [comment]
@bonrails Can you please try it again? I deleted and reuploaded the tar.gz

**Pull request merged**
