### PR TITLE
Update documentation for cache clean with multiple parameters

### PR DESCRIPTION
**Pull request by lankaapura**
Related: https://github.com/yarnpkg/yarn/issues/5273

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit 380e5478e350c056ccc5e85c9a8364d866107429

https://deploy-preview-764--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
Will merge when https://github.com/yarnpkg/yarn/pull/5297 is shipped :) please feel fee to ping me if I forgot

**Comment by Haroenv** [comment]
@bestander, should we merge it now it’s in master, or when it’s in a new version?

**Comment by bestander** [comment]
Let's do it now to free some memory in our brains :)

**Pull request merged**
