### PR TITLE
Always show the latest avatar

### PR DESCRIPTION
**Pull request by u3u**

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit 7081f3d48cf032b21842efca3b6da921e852eba0

https://deploy-preview-753--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
Now the image fetched will be bigger and not compressed though, I’m not sure if we should do this.

**Comment by Haroenv** [comment]
So a usual search page is about 500kb bigger 😕, does GitHub have api parameters to get a smaller version? 

compare page size of: https://deploy-preview-753--yarnpkg.netlify.com/en/packages?q=t&p=1 with the current version of https://yarnpkg.com/en/packages?q=t&p=1

I think we should just periodically remove stale caches

**Comment by u3u** [comment]
Through the user's ID can get the user's avatar, parameter "s" can be set to obtain the avatar size.
Example: [https://avatars2.githubusercontent.com/u/{uid}?s={size}&v=4](https://avatars2.githubusercontent.com/u/20062482?s=50&v=4)

avatar

However, you can not get the avatar by user name directly and set the size. 
Github provides APIs for getting user information, By user name you can get the user's ID and avatar.

> https://api.github.com/users/u3u

```json
{
  "login": "u3u",
  "id": 20062482,
  "avatar_url": "https://avatars2.githubusercontent.com/u/20062482?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/u3u",
  "html_url": "https://github.com/u3u",
  "followers_url": "https://api.github.com/users/u3u/followers",
  "following_url": "https://api.github.com/users/u3u/following{/other_user}",
  "gists_url": "https://api.github.com/users/u3u/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/u3u/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/u3u/subscriptions",
  "organizations_url": "https://api.github.com/users/u3u/orgs",
  "repos_url": "https://api.github.com/users/u3u/repos",
  "events_url": "https://api.github.com/users/u3u/events{/privacy}",
  "received_events_url": "https://api.github.com/users/u3u/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": "@MoeFE ",
  "blog": "https://quq.cat",
  "location": "Shanghai, China",
  "email": null,
  "hireable": null,
  "bio": "享受血賺的時刻 管它三年哪裡過",
  "public_repos": 6,
  "public_gists": 1,
  "followers": 23,
  "following": 1,
  "created_at": "2016-06-21T08:13:54Z",
  "updated_at": "2018-01-11T14:34:19Z"
}
```

Here you can set the avatar size, but a bit of trouble.

Now the avatar cache time is too long, 
can you set the browser to force the refresh request the latest avatar?

**Comment by Haroenv** [comment]
hmm, yes that sounds less efficient, and not doable to do on every character, I'll just change the cache time to be lower. Thanks for your contributions

**Comment by Haroenv** [comment]
The setup has been done on Cloudinary to invalidate the cache. It will only be stale for maximum 7 days now. I'll close this PR and the issue in a week when everything is updated, okay?

**Comment by u3u** [comment]
Okay thank you!

**Pull request closed without merging**
