### PR TITLE
Fix the reference comparison in the optimization code snippet

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview failed.

Built with commit 8f37f18d4bf2f1d67db21781477d683f2575dc69

https://app.netlify.com/sites/yarnpkg/deploys/59afe14f0752d04a0eec824f

**Comment by stof** [comment]
well, I'm not allowed to see the report you linked, so I cannot know whether it is related to my change

**Comment by Haroenv** [comment]
Yes, this was an automatic comment, it's probably not because of your change, I'm sorry

**Comment by Haroenv** [comment]
yay, I managed to get the deploy preview to work, thanks for your help @stof

**Comment by arcanis** [comment]
Thanks @stof!

**Pull request merged**
