### PR TITLE
added global bin folder to PATH

### PR DESCRIPTION
**Pull request by bestander**
I prefer using install.sh script for managing Yarn on my Raspberry Pi.
This seems to work both for Mac and a Raspbian OS.

@Daniel15, does it look reasonable?

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview ready!

Built with commit 9a0ecb4556fb9e60137ba07db28b2b4f2a345e53

https://deploy-preview-750--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
I like it!

**Comment by bestander** [comment]
All right, better sorry than safe.
Let's merge and see what happens.
I consider @Haroenv's response as a review :)

**Comment by Daniel15** [comment]
This looks good to me, although I thought that Yarn was supposed to create symlinks from `~/.yarn/bin` to point to files in `~/.config/yarn/global/node_modules/.bin`

**Comment by bestander** [comment]
Didn't really work when I was installing global libraries with Yarn in Raspbian.
Maybe we need to add ~.yarn/bin to PATH instead?

**Pull request merged**
