### PR TITLE
make background of images transparent

### PR DESCRIPTION
**Pull request by Haroenv**
The images now have a white background, but by replacing it with a transparent background, it is also about 80kb smaller, which will have a small positive impact on the page.

By the way, if you read this Shitty Watercolour, I really like the images

### CODE REVIEW

**Comment by thejameskyle** [comment]
The feathering around the colors removes just a little bit too much where you can tell it is cut out. Could you soften and pull it out a bit?

**Comment by Haroenv** [comment]
Sure, I'll redo the changes with a little more feathering. When looking at it side-by-side it's clear that I removed a little too much

**Comment by Haroenv** [comment]
I can't see the difference in the previews now (except that in my version the robot cat doesn't cover the lines, but that's better). The difference in size is now about 70k

**Comment by thejameskyle** [comment]
Thanks!

**Comment by Haroenv** [comment]
With pleasure ❤️

**Pull request merged**
