### PR TITLE
Bump version to 0.18.0

### PR DESCRIPTION
**Pull request by Daniel15**
cc @bestander

### CODE REVIEW

**Comment by bestander** [comment]
Let's wait a bit, there is a regression in linking of optional deps

**Comment by Daniel15** [comment]
Is there a way to mark 0.18.0 as RC on npm in that case?

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>

**Comment by bestander** [comment]
Not sure, can we add tags to existing releases?
We need to do everything by default next time

**Comment by Daniel15** [comment]
Not sure, I'm not very familiar with npm

I filed https://github.com/yarnpkg/yarn/issues/2161 to handle RC releases.

**Comment by Daniel15** [comment]
@bestander I think I did it correctly:
```
npm dist-tag add yarn@0.18.0 rc
npm dist-tag add yarn@0.17.10 latest
```
Seems to have worked.

```
C:\Users\danlo
λ npm dist-tag ls yarn
latest: 0.17.10
rc: 0.18.0
```

Now `npm install -g yarn` installs `0.17.10` and `npm install -g yarn@rc` installs `0.18.0`.

**Comment by bestander** [comment]
Awesome, thanks, Daniel!

**Comment by Daniel15** [comment]
0.18.1 is out, closing this as it's stale.

**Pull request closed without merging**
