### PR TITLE
Moved search to documentation index page

### PR DESCRIPTION
**Pull request by dhruvdutt**
Resolving #230 

There's an issue in autocomplete results view.
The `z-index` property seems alright still it isn't filling up the area properly.

screenshot from 2016-11-03 18-11-01

screenshot from 2016-11-03 17-49-45

### CODE REVIEW

**Comment by thejameskyle** [comment]
It's not an issue with `z-index`, the `.hero` section has an `overflow: hidden` on it. 

Could you actually move it down into the body like this though:
 
screen shot 2016-11-03 at 11 25 02 am

**Comment by dhruvdutt** [comment]
Thanks for the design. I'll on it.

**Comment by dhruvdutt** [comment]
screenshot from 2016-11-04 00-51-26

**Comment by dhruvdutt** [comment]
screenshot from 2016-11-04 01-17-10

**Comment by thejameskyle** [comment]
Sorry, I got to tweaking and made a bunch of changes

**Comment by dhruvdutt** [comment]
Seems perfect! :100:

**Comment by hpurmann** [comment]
What do you guys think of having the search bar in the header as well? See https://github.com/yarnpkg/website/issues/284

**Pull request merged**
