### PR TITLE
Pattern docs

### PR DESCRIPTION
**Pull request by philquinn**
Adds documentation about the new pattern flag on a few commands.

@arcanis I guess this can't really be merged until that feature is released though.

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview ready!

Built with commit 4bb0fc00cb8055053d32e234156e35407364e77b

https://deploy-preview-671--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
looks good, let's ping this PR when the feature is released

**Comment by philquinn** [comment]
@Haroenv  thanks for reviewing. New version of yarn was released yesterday. So this should be good to merge.

**Comment by Haroenv** [comment]
awesome, thanks for your contribution @philquinn

**Pull request merged**
