### PR TITLE
Add Aloglia Search Placeholder

### PR DESCRIPTION
**Pull request by JoelMarcey**
We won't get a public Algolia id until we go public with the site. But we can use the Nuclide id for testing, etc.

I am not a CSS expert, so if there are any color or positioning changes, we can make modifications as we go along.

We can easily remove this from `navigation.html` right before we launch, get the id, then add it back when we get the id.

**Default on Navbar**

screenshot 2016-09-28 14 59 36

**When Searching**

screenshot 2016-09-28 14 59 45

### CODE REVIEW

**Comment by pborreli** [comment]
maybe replace `Aloglia` by `Algolia` for commit/PR/changelog history sake

**Comment by JoelMarcey** [comment]
Closing this one in favor of a new one.....

**Comment by JoelMarcey** [comment]
oh sure. can do that.

**Comment by JoelMarcey** [comment]
I did spell it wrong in the actual committed pull request though -- https://github.com/yarnpkg/website/commit/ff8bb6cf9bdbd769132b38b27d20e378f22e560d

Sorry about that. I was moving too fast.

**Comment by pborreli** [comment]
You still can edit it, with commit --amend for example

**Comment by JoelMarcey** [comment]
I think that would require a force push, which I don't want to do because it changes the commit hashes.

https://help.github.com/articles/changing-a-commit-message/

**Comment by cpojer** [comment]
It's ok, we'll survive with the typo.

**Pull request closed without merging**
