### PR TITLE
Docs: Fix typo error

### PR DESCRIPTION
**Pull request by zddhub**

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit 0487e4b8a24dcdc68e21db2a5349870c9fa10dac

https://deploy-preview-830--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
It's actually correct; not an error. In package.json we have `scripts: test: jest`. This means that if we `yarn run test --something`, it will run `jest --something`. 

To make it more clear; another example:

```json
{
  "scripts": { "test": "tap"}
}
```
```sh
yarn run test --color
# same as
tap --color
```

Thanks for your contribution anyway!

**Comment by zddhub** [comment]
Got it, thanks for explanation!

**Comment by Haroenv** [comment]
Have a great day and all contributions are definitely welcome ❤️

**Pull request closed without merging**
