### PR TITLE
fix Chinese language code

### PR DESCRIPTION
**Pull request by justjavac**

### CODE REVIEW

**Comment by Haroenv** [comment]
Hi @justjavac, thanks for  your contribution, this definitely looks correct, but I'm not fluent in Chinese languages, so I can't properly review. I'm going to ask around to see if I can verify the info

**Comment by cht8687** [comment]
this fix is correct.

**Comment by Haroenv** [comment]
thanks!

**Comment by hax** [comment]
It seems `zh-sg` should still under `zh-Hans`.

**Comment by cht8687** [comment]
thanks for correcting @hax 
didn't know zh-sg is under zh-Hans.

**Comment by Haroenv** [comment]
that was fixed by @wongmjane in #990 :)

**Pull request merged**
