### PR TITLE
Document new global upgrade comand introduced by ebe899382fdb70222651380f299737c6625d87e4

### PR DESCRIPTION
**Pull request by markstos**

### CODE REVIEW

**Comment by Haroenv** [comment]
Thanks!

**Comment by markstos** [comment]
Why didn't you use my commit which also updated `en/docs/cli/global.md`?

Ref: https://github.com/yarnpkg/website/pull/236/commits/a8683bea9d734d04107f4af6f7cc56b1f041c9ea

**Comment by Haroenv** [comment]
That already happened in some other commit, right?

**Comment by markstos** [comment]
Ah, looks like it.

**Pull request closed without merging**
