### PR TITLE
Move nightly builds page to site

### LINKED ISSUE #259: Merge in nightly builds page
https://nightly.yarnpkg.com/

@Daniel15 Any reason this can't be a page on the normal website? The styles and layout have already gone out of sync.

If there's something dynamic you could just turn it into a JSON api that we can fetch from.

### PR DESCRIPTION
**Pull request by Daniel15**
Moves the page at https://nightly.yarnpkg.com/ onto the main site. The list of available builds is loaded via an AJAX request from the nightly build server.

Once this lands, I'll make https://nightly.yarnpkg.com/ redirect to it and kill that old page. It was mainly for prototyping some ideas 😄 

cc @thejameskyle 

Closes #259

### CODE REVIEW

**Comment by thejameskyle** [comment]
I'm not sure this should be in the getting started guide. I'm tempted to just leave it as a link on the install page unless there's a better place for it

**Comment by Daniel15** [comment]
I wasn't sure where to put it. Should I just remove the link from ` _data/guides.yml`?

**Comment by thejameskyle** [comment]
Yeah I think that would be best, eventually I'll do a slight reorganization of some stuff and include it in another guide

**Comment by thejameskyle** [comment]
Awesome work on this page btw, it looks really great

**Pull request merged**
