### PR TITLE
Improve Docs

### PR DESCRIPTION
**Pull request by kundanku505**

### CODE REVIEW

**Comment by arcanis** [comment]
Hey @kundanku505 - may I ask which school you belong to that asked you to make this PR?

**Comment by kundanku505** [comment]
College student

**Comment by arcanis** [comment]
That's interesting - did you get like a tutorial explaining you how to contribute? I'd be curious to see what that looks like 🤔

**Comment by kundanku505** [comment]
My pleasure 😊

**Comment by arcanis** [comment]
Assuming you put it in attachment, they don't seem to get forwarded by GitHub 😃

**Comment by kundanku505** [comment]
😊😊

**Pull request closed without merging**
