### PR TITLE
Add Gentoo Linux install instructions

### PR DESCRIPTION
**Pull request by Bigfootjon**
Yarn is available on Gentoo's portage package manager (1), and I
have a pending patch to yarn to provide correct install instructions
from within the yarn cli (2).

(1) https://packages.gentoo.org/packages/sys-apps/yarn
(2) https://github.com/yarnpkg/yarn/pull/7123

### CODE REVIEW

**Comment by Haroenv** [comment]
looks like we will need a fallback for languages not yet translated here too, like for install-ci

**Comment by Bigfootjon** [comment]
@Haroenv are you referring to the `file_exists` tag? (added in https://github.com/yarnpkg/website/commit/fe50d77f15a90dbb27be13b7edb6ee59ef1a402b)

**Comment by Haroenv** [comment]
Yes, it's a bit of a hacky workaround, but is needed because of the i18n implementation

**Comment by Bigfootjon** [comment]
Well the build succeeds now but the deploy preview doesn't show any install instructions. @Haroenv Is this expected?

**Comment by Haroenv** [comment]
That's not expected, and likely an error in the (fairly hacky) workaround for missing files. Unfortunately I don't really have time to look into this _right now_

**Comment by Bigfootjon** [comment]
I was able to fix the missing install documentation. Turned out to be a flaw with the implementation of  `file_exists` where it didn't strip trailing whitespace, I've inserted a commit to fix that but if you would rather I can split it out into a separate PR **or** I can rewrite my changes to match the style of the other use of `file_exists` (i.e. without whitespace around the file path)

**Comment by Haroenv** [comment]
Thanks for the effort you put in this!ç

**Comment by Bigfootjon** [comment]
Happy to help!

**Pull request merged**
