### PR TITLE
remove new tab from package detail links

### PR DESCRIPTION
**Pull request by transitive-bullshit**
addresses #794

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit 8a1b897072c5ccaf1e157e30488102810d13087e

https://deploy-preview-796--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
Did you intend to also change the target on the hits?

**Comment by transitive-bullshit** [comment]
I'm not sure what you mean by hits, as I don't see the term used in this source.

As far as I can tell, all of the links on the package detail page which used to be new tabs should now be regular.

**Comment by Haroenv** [comment]
Yes, but in your issue you were talking about the search results (hits), right?

**Comment by transitive-bullshit** [comment]
Ahhh no, I was talking about the package detail pages which are already 1-level deep and having them `target=blank` at that point is pretty annoying.

Would you be open to considering this PR as-is and then we can discuss hit functionality in a separate issue?

**Comment by transitive-bullshit** [comment]
Actually, I was just looking at it, and I can't see anywhere on the hits where `target=blank` is used.  So as far as I can tell, the hit links currently work as expected and it's just the package detail page that needs changing.

**Comment by Haroenv** [comment]
Great! Sorry for the initial confusion

**Pull request merged**
