### PR TITLE
Add audit command exit code details for yarnpkg/yarn#6819

### PR DESCRIPTION
**Pull request by rally25rs**
Documentation for the change made by https://github.com/yarnpkg/yarn/pull/6819/

Adds specific exit codes to `yarn audit` command.

### CODE REVIEW

**Comment by Haroenv** [comment]
Looks good, will merge if released

**Comment by antrew** [comment]
Can this pull request please be merged? It will answer questions in multiple currently open issues regarding the exit code of yarn audit.

**Comment by Haroenv** [comment]
can you link the related issues if you have them @antrew ?

**Comment by antrew** [comment]
@Haroenv I misinterpreted some open issues, so there is only this one open:
* https://github.com/yarnpkg/yarn/issues/7260

This one was closed, but probably would not have been opened if this pull request was merged:
* https://github.com/yarnpkg/yarn/issues/7174

**Pull request merged**
