### PR TITLE
Solve issue of missing navigation in docs/cli/generate-locker-entry

### PR DESCRIPTION
**Pull request by akshatjain1995**
Solved issue #113

### CODE REVIEW

**Comment by montogeek** [comment]
LGTM!

**Comment by akshatjain1995** [comment]
So Will you commit these changes @montogeek ?

**Comment by montogeek** [comment]
@akshatjain1995 I can't, I am not an owner on this repo, I just reported the error :)

**Comment by akshatjain1995** [comment]
@JoelMarcey will you commit these changes ?

**Comment by addyosmani** [comment]
@thejameskyle suggested editing https://github.com/yarnpkg/website/blob/master/_data/guides.yml#L54 instead IIRC. Both updating that file or this one seem fine to me, but will see what he thinks.

**Comment by montogeek** [comment]
@addyosmani All ids on `guides.yml` are snake_case

**Comment by addyosmani** [comment]
You are indeed correct. With that in mind, this looks fine to merge.

**Comment by cpojer** [comment]
thank you! Oops, my mistake.

**Pull request merged**
