### PR TITLE
added documentation for cli command upgrade-interactive

### PR DESCRIPTION
**Pull request by bobmoff**
hope i haven't missed anything

### CODE REVIEW

**Comment by Daniel15** [comment]
Thanks! @torifat would you be able to have a quick look?

**Comment by bestander** [comment]
Let's get it merge and fix if anything is wrong

**Comment by torifat** [comment]
@Daniel15 LGTM. Sorry, I didn't notice your tag 😞

**Comment by bobmoff** [comment]
How does this work? Is merge == release ?

**Comment by Daniel15** [comment]
@bobmoff - Website changes that are merged should appear right away. It's live now: https://yarnpkg.com/en/docs/cli/upgrade-interactive

**Comment by bobmoff** [comment]
@Daniel15 Ok. I checked it right after the merge, but then it wasn't there, but now it is. 👍

**Comment by Daniel15** [comment]
It can take a few minutes for the site to build 😃

**Pull request merged**
