### PR TITLE
Mobile menu fixes

### PR DESCRIPTION
**Pull request by danielhusar**
Fixes:
screen shot 2017-10-22 at 19 51 57

To:
screen shot 2017-10-22 at 20 04 27
screen shot 2017-10-22 at 20 04 33

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview ready!

Built with commit a48699939e7db697a4613414bcfd339a660ccfb2

https://deploy-preview-688--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
Which browser were you seeing your screenshots on? I see the collapsed version in both yours and the real site. 

Thanks!

**Comment by danielhusar** [comment]
Both desktop chrome and iOS safari.
d316f9b4-3b88-45ee-bb1f-d91bf8d3a7d5

**Comment by Haroenv** [comment]
Still can't see it happen, but since your fix didn't break anything, let's merge :shipit: 

screen shot 2017-10-23 at 17 46 25

**Comment by danielhusar** [comment]
Weird :) You screen doesn't show expanded nav though :) Thanks!

**Comment by Haroenv** [comment]
Oh! now I get what I should've been looking at! Thanks!

**Pull request merged**
