### PR TITLE
Webpack config

### PR DESCRIPTION
**Pull request by ink8bit**
## Changes
Slightly refactored `webpack` configuration

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview failed.

Built with commit 16a4f06063ec8ef89812ec62ac379118c51bf53e

https://app.netlify.com/sites/yarnpkg/deploys/599d16796f4c502b483f5ce8

**Comment by Haroenv** [comment]
Seems like the build fails. Did you try it locally? Thanks by the way!

**Comment by Haroenv** [comment]
Hey, no idea why this failed, it works perfectly in #607. Thanks a lot!

**Comment by ink8bit** [comment]
@Haroenv You're welcome!

**Pull request merged**
