### PR TITLE
Added api doc about workspaces run command

### PR DESCRIPTION
**Pull request by kwelch**
I opened yarnpkg/yarn#6244 to add the ability to run a command on all workspace. 

This is the related documentation update.

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit f55130e4f6b213177c1ba19a457182125e3f5c86

https://deploy-preview-855--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
Thanks Kyle, please comment here when the PR is merged in Yarn so we can merge the docs :)

**Comment by kwelch** [comment]
The prerequisite PR was merged, but it has not released yet. It looks like it will be park of the 1.10 release.

**Comment by Haroenv** [comment]
perfect!

**Comment by kwelch** [comment]
v1.10 has released, I think we are safe to merge this when ready.

**Comment by Haroenv** [comment]
Thanks for the ping Kyle!

**Pull request merged**
