### PR TITLE
Add open graph information

### LINKED ISSUE #115: Site should have og:graph meta tag
Currently it looks pretty bad when shared on Facebook - There's no image.

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fyarnpkg.com%2F

### PR DESCRIPTION
**Pull request by JoelMarcey**
Fixes #115

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Example header content...

```
    <meta property="og:url" content="https://yarnpkg.com/" />
    <meta property="og:site_name" content="Yarn"/>
    <meta property="og:title" content="Yarn" />
    <meta property="og:image" content="https://yarnpkg.com/assets/og_image.png" />
    <meta property="og:description" content="Fast, reliable, and secure dependency management." />
```

**Comment by Daniel15** [comment]
Thanks! :D 

Is the image the right size/dimensions?

**Comment by JoelMarcey** [comment]
Does it get scaled? I noticed a lot of our other og images for other sites are pretty big in their raw form too.

**Comment by Daniel15** [comment]
The dev site says:

> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. 

https://developers.facebook.com/docs/sharing/best-practices#images

Not sure if that's up-to-date though as the example screenshot is super old.

I just tested with the debugger (after this was merged) and it looks like it's not the right aspect ratio as the sides get cut off :(



Might just need to add some whitespace to the top and bottom of the image.

**Comment by JoelMarcey** [comment]
Oh - I am 1239 x 556. I can fix that.

**Comment by JoelMarcey** [comment]
I reduced the size from double that. Because it was huge! I will go 75% then :)

**Comment by JoelMarcey** [comment]
https://github.com/yarnpkg/website/pull/119

**Comment by benmann** [comment]
Always thought it just needs to be 16:9 or 4:3 with some space to each side.

**Comment by JoelMarcey** [comment]
Aspect ratio seems to be 1.91:1 or something...

http://stackoverflow.com/questions/24216838/webpage-ogimage-are-cropped-in-facebook

**Pull request merged**
