### PR TITLE
fix(redirects): explicitly route /packages/ to /packages/

### PR DESCRIPTION
**Pull request by Haroenv**
For some reason, Netlify interprets /en/packages/ to match /:lang/package/*, so this here will override that behaviour

(waiting on the deploy preview to see if it does the job)

### CODE REVIEW

**Comment by Haroenv** [comment]
Doesn’t work 😢

**Comment by Haroenv** [comment]
closing for now, since it doesn’t seem to help

**Comment by Haroenv** [comment]
This is working now; see https://fix-redirect-packages--algolia-yarn.netlify.com/en/packages

quote from Netlify support:

>Hi there,

>Sorry for the slow reply - had to check in with a guru on this one.  He found the bug and is working on a fix for it, but in the meantime, if you put that redirect at the very top of the file when you deploy, it should work even before we roll the bugfix out.

>Let me know in case that isn't the case!

**Comment by vvo** [comment]
👌

**Comment by Daniel15** [comment]
Thanks!

**Comment by jdalton** [comment]
Awesome! I :heart: Netlify folks.

**Pull request merged**
