### PR TITLE
Clarify what Yarn is package managing

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
Relevant page: https://deploy-preview-961--yarnpkg.netlify.com/en/docs/getting-started

**Comment by Haroenv** [comment]
I feel like `node_modules` is more relevant there, since other code can also be used for other languages

**Comment by Haroenv** [comment]
Is this something you were confused about?

**Comment by fulldecent** [comment]
I was confused. 

---

I stared my journey by wanting to get involved with this project https://github.com/wighawag/ethereum_gas/tree/24bd188002e8fd077ad0dcebb6bc6de97c0d9bdd

Then my next question was what is Yarn.

Then I found https://yarnpkg.com/en/docs/getting-started

At this point, I don't even know what language I'm supposed to be thinking in. And at this point I am three questions deep in trying to start a new project. This PR hopes to reduce the recursion depth necessary to grok yarn.

**Comment by Daniel15** [comment]
Yarn can be used for packages other than JavaScript though - For example you can manage CSS frameworks (eg. Bootstrap) with it, and I think Reason may use it (or at least parts of it?) too.

**Comment by fulldecent** [comment]
How about:

> Yarn is a package manager for your JavaScript and CSS code. It allows you to use and share code...

**Comment by fulldecent** [comment]
Looks good, I see this is life now, because

**Pull request closed without merging**
