### PR TITLE
svg search icon

### PR DESCRIPTION
**Pull request by Haroenv**
Replaces the png search icon by one in svg (created by me, no copyright). 

I couldn't get the website to build locally, can someone check for me if this change works of if the `background-size` should be `contain`.

### CODE REVIEW

**Comment by wyze** [comment]
Hey @Haroenv, in regards to checking your changes since you couldn't locally. When you submit a PR, the check that it runs will actually deploy the code to a site so everyone can use.

Below, click the link that says, `Show all checks`. Then click `Details` next to `deploy/netlify` that becomes available!

**Comment by Haroenv** [comment]
Oh that's nice, that preview deploy looks great. My PR seems to be working! Thanks @wyze

**Comment by thejameskyle** [comment]
Oh thank you thank you, this was driving me crazy

@Haroenv Can you give more detail about why you are unable to build the website?

Also, there's another issue that's been bothering me if you want to fix it:

At certain screen resolutions the search input does this on focus:

screen shot 2016-10-24 at 8 38 20 am

**Comment by Haroenv** [comment]
I'll try to recreate that issue and fix it when I have time for it, bur for the record, I think that that's a separate problem. 

I wasn't able to run `make` or `jekyll build` because I couldn't get `ffi` installed. It's a dependency of `jekyll`, which is kinda weird, since `jekyll` works globally as well as via `bundler` in other projects of mine. 

<details>
<summary>output of make</summary>
```
$ make
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using addressable 2.4.0
Using colorator 1.1.0
Installing ffi 1.9.14 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20161024-88356-15i5bae.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... no
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/extensions/universal-darwin-16/2.0.0/ffi-1.9.14/mkmf.log

current directory: /Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c
make "DESTDIR="
mkdir -p "/Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c"/libffi-i386; (if [ ! -f "/Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c"/libffi-i386/Makefile ]; then echo "Configuring libffi for i386"; cd "/Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c"/libffi-i386 && env CC=" xcrun clang" CFLAGS="-arch i386 " LDFLAGS="-arch i386" "/Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c/libffi"/configure --disable-static --with-pic=yes --disable-dependency-tracking --host=i386-apple-darwin > /dev/null; fi); env MACOSX_DEPLOYMENT_TARGET=10.4 /Applications/Xcode.app/Contents/Developer/usr/bin/make -C "/Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c"/libffi-i386
Configuring libffi for i386
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/gawk
  Reason: image not found
./config.status: line 1281: 90044 Done(141)               eval sed \"\$ac_sed_extra\" "$ac_file_inputs"
     90045 Abort trap: 6           | $AWK -f "$ac_tmp/subs.awk" > $ac_tmp/out
config.status: error: could not create include/Makefile
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** ["/Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14/ext/ffi_c"/libffi-i386/.libs/libffi_convenience.a] Error 2

make failed, exit code 2

Gem files will remain installed in /Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/gems/ffi-1.9.14 for inspection.
Results logged to /Users/haroenv/git/website-2/vendor/bundle/ruby/2.0.0/extensions/universal-darwin-16/2.0.0/ffi-1.9.14/gem_make.out
Using forwardable-extended 2.6.0
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.12.0
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.12.5
An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.
make[1]: *** [install] Error 5
make: *** [start] Error 2
```
</details>

Also had some trouble because the `.gitmodule` had it's url declared via `git@github.com`, and not via `https`. 

Probably wiping a whole bunch of packages I have installed globally and reinstalling would fix it, but it didn't work for me.

**Comment by Haroenv** [comment]
@thejameskyle your problem is fixed by changing 

```css
@media screen and (max-width: 1085px) {
  input#algolia-doc-search:focus {
    width: 178px;
  }
}
```

to 

```css
@media screen and (max-width: 1200px) {
  input#algolia-doc-search:focus {
    width: 178px;
  }
}
```

because that's the actual size it should get smaller at. I'll open a separate PR for that

**Pull request merged**
