### PR TITLE
Babel-preset-env

### PR DESCRIPTION
**Pull request by ink8bit**
# babel-preset-env
More info: 
- http://babeljs.io/docs/plugins/preset-env/#how-it-works
- https://github.com/babel/babel-preset-env

## Changes
- Added `babel-preset-env`
- Removed `babel-preset-es2015`

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview failed.

Built with commit 5ca948eaea6d8180cb7496885a740194928ecdc5

https://app.netlify.com/sites/yarnpkg/deploys/59a043f76f4c504de85bf034

**Comment by Haroenv** [comment]
Annoying, the build failed for the same reason as last time. I'll check in person, wanted to do this change myself too!

**Comment by ink8bit** [comment]
Would be nice! 
I've tested locally and all was good.
Thank you!

**Comment by Haroenv** [comment]
It works locally for me as well. Thanks a lot!

**Comment by Haroenv** [comment]
Works perfect in the preview now

**Pull request merged**
