### PR TITLE
Document that yarn global bin needs to be added to $PATH

### PR DESCRIPTION
**Pull request by Fahrradflucht**
See https://github.com/yarnpkg/yarn/issues/648

### CODE REVIEW

**Comment by Fahrradflucht** [comment]
I thought about adding a recommendation on how to do this ( like adding `export="${PATH}:$(yarn global bin)"` to your shell config, but I think since this works completely different on Windows (IIRC) I omitted that.

**Comment by cpojer** [comment]
cc @kittens – can we make it so we put our global bins into `/usr/local/bin` just like npm does? I think that'll be much easier for people.

**Comment by Fahrradflucht** [comment]
@cpojer wouldn't that have the issues discussed [here](https://github.com/creationix/nvm/issues/668)?

**Comment by Daniel15** [comment]
This is already documented in the installation instructions: https://yarnpkg.com/en/docs/install. See "path setup" on the Mac OS and Linux tabs, and on Windows the installer modifies the path automatically.

**Comment by Fahrradflucht** [comment]
Ah I see. Based on the issue I was referring to, this gets missed sometimes anyway. Do you think I should change it to a little note to make sure that this done on Mac/Linux or do you think it should just be closed all together?

**Comment by tomchentw** [comment]
Thank @Fahrradflucht. I need to add this to my `.zshrc` to make it work on my computer.

To clarify, here's my `npm/node/yarn` install steps:

1. Install `npm` independently with curl script
2. Install `node` with `homebrew` by this command: `brew install node --without-npm`
3. Install `yarn` with `homebrew`: `brew install yarn`

After these steps, my result for `yarn global bin` is:

```
/usr/local/Cellar/node/6.9.1/bin
```

It's not under `~/.yarn/bin` as [the document suggests](https://yarnpkg.com/en/docs/install).

As such, I'll need to modify my `.zshrc` as follows:

```
export PATH="$(yarn global bin):$PATH"
```

Hope someone will find this helpful.

**Comment by carhartl** [comment]
Running ``export PATH="$PATH:`yarn global bin`"`` as suggested by the installation instructions slows down my shell startup noticeably , e.g. time to type. Is there a way to setup the path in a "static" way, while avoiding having to update my dotfiles each time a new node version is installed (`"$PATH:/usr/local/Cellar/node/7.3.0/bin"` => `"$PATH:/usr/local/Cellar/node/7.4.0/bin"`)?

**Comment by carhartl** [comment]
... figured out where to look for: `export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"`

**Comment by Haroenv** [comment]
Sorry for the massive delay on this PR. With the current content this isn't necessary anymore I think. Feel free to reopen and I promise to look at the issues earlier

**Comment by ianchanning** [comment]
I've just hit this issue, there is nothing documenting that you need to add something to your `$PATH` to get `yarn global add` to work. I think this PR is still valid.

The current documentation seems to work around it by specifying that you must use a `prefix` argument. But then libraries such as [Bucklescript installation][1] (and ReasonML) use the default syntax:

```sh
yarn global add bs-platform
```

I raised a [ReasonML issue #2168][2] about the undocumented requirement for adding something to your path for `yarn global add`, but they then claim that it is an issue with yarn.

[1]: https://bucklescript.github.io/docs/en/installation
[2]: https://github.com/facebook/reason/issues/2168

**Pull request closed without merging**
