### PR TITLE
Enable Ukrainian Translation on site

### PR DESCRIPTION
**Pull request by gladimdim**
Ukrainian Translation is 92% complete. I constantly update new translations on crowdin. It would be good to enable it on production site.

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit c9482350fa30202051afc9ab017b572862d0e745

https://deploy-preview-765--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
Great idea! I didn't notice it was that complete already, thanks for your efforts!

**Comment by gladimdim** [comment]
Great news! Thank you!

**Comment by Haroenv** [comment]
#766 seems to have been broken by a string translated here `layout: довідник` should have been `layout: guide` but I can't seem to find the actual string

**Pull request merged**
