### PR TITLE
Bump versions of yarn to latest release

### PR DESCRIPTION
**Pull request by jure**

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview for *yarnpkg* ready!

Built with commit 466314b31c7e3393e6905beaacb639e726b362b1

https://deploy-preview-783--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
This should be done automatically by @DanBuild , cc @Daniel15

**Comment by Daniel15** [comment]
I'll take a look soon.

**Comment by Daniel15** [comment]
Neither of these releases are complete - They're missing the Windows build. Bumping the version would break the Windows installer download.

cc @arcanis  - Do you know what happened with 1.5.0?

**Comment by Daniel15** [comment]
Seems like there's a huge queue on AppVeyor. I cancelled all pending builds before the 1.5.0 build, so hopefully it completes soon.

**Comment by SEAPUNK** [comment]
Looks like AppVeyor is stuck in general? That job seems to be the only queued job, but it's stuck at "queued".

**Comment by Daniel15** [comment]
Seems like a known issue with AppVeyor at the moment: https://help.appveyor.com/discussions/problems/3995-builds-are-queued. I'll ping their support team.

**Comment by jure** [comment]
👍 Sorry, I seem to have not read the comments in that file, 2 lines above the line I was changing. :)

Looks like the version still hasn't been updated, though.

**Comment by Daniel15** [comment]
Here's an example of one of the automated commits: https://github.com/yarnpkg/website/commit/cdc247f7526846b72e78233e610064ede0638f7b

**Pull request closed without merging**
