### PR TITLE
Change ?json to ?meta in Unpkg API call

### LINKED ISSUE #614: Browse files doesn't seem to work
Hi, I tried opening the file listing for https://yarnpkg.com/en/package/qs, and I got an error message: `Could not load file listing: Unexpected token < in JSON at position 0`. I got the same thing in incognito mode. Firefox gave me `Could not load file listing: JSON.parse: unexpected character at line 1 column 1 of the JSON data`, and Safari gave me `Could not load file listing: The string did not match the expected pattern.`. I tried other packages (webpack and left-pad), and they produced the same errors for me.

It looks like it's making a request to the GitHub API, and the JSON response looks okay, though I don't see any file info.

### PR DESCRIPTION
**Pull request by Daniel15**
This was renamed at some point

Fixes #614

### CODE REVIEW

**Comment by Daniel15** [comment]
Waiting for Netlify build to test it.

**Comment by Haroenv** [comment]
Deploy preview failed.

Built with commit ca0070f2ff88c179786772507353166d0e1827a8

https://app.netlify.com/sites/yarnpkg/deploys/59a5c2becf321c1c7296dbb5

**Comment by Daniel15** [comment]
Tested the preview and it works!

https://deploy-preview-615--yarnpkg.netlify.com/en/package/qs

**Comment by Haroenv** [comment]
It's live now. Thanks!

**Pull request merged**
