### PR TITLE
ModifiedDoc

### PR DESCRIPTION
**Pull request by mohitlovecoding**

### CODE REVIEW

**Comment by Haroenv** [comment]
Closing, since it seems like you're just learning how GitHub works. We're definitely welcoming any real changes you want to suggest though!

**Comment by Trott** [comment]
@Haroenv You might want to [add an `invalid` label](https://hacktoberfest.digitalocean.com/details/#spam) to this one.

**Comment by Daniel15** [comment]
Interestingly, I'm seeing a lot of PRs similar to this one today, even in my personal repos that are mostly otherwise unknown. I wonder why? Is there some sort of coding class that people are following that involves submitting PRs?

**Comment by Trott** [comment]
> Interestingly, I'm seeing a lot of PRs similar to this one today, even in my personal repos that are mostly otherwise unknown. I wonder why? Is there some sort of coding class that people are following that involves submitting PRs?

@Daniel15 Yes, Hacktoberfest. You'll want to label those PRs as `invalid` or `spam` to keep people from getting free t-shirts for opening them. 😔

**Comment by Trott** [comment]
@Daniel15 It's the start of Hacktoberfest. You'll want to add the `invalid` or `spam` label to those PRs. https://hacktoberfest.digitalocean.com/details/#spam

**Pull request closed without merging**
