### PR TITLE
Image Placement bug & optimization

### PR DESCRIPTION
**Pull request by una**
Just some small tweaks. I noticed the image overlapped on the medium media query, so I removed the top margin:

Before:
screen shot 2016-10-12 at 9 54 02 am

After:
screen shot 2016-10-12 at 10 03 50 am

And running the images through an optimizer saved ~ 388kb :)

### CODE REVIEW

**Comment by Daniel15** [comment]
Interesting, which optimizer did you use? I already ran the images through TinyPNG in https://github.com/yarnpkg/website/pull/95 (I tried Zopfli but TinyPNG had better results).

**Comment by una** [comment]
@Daniel15 ImageAlpha

**Comment by thejameskyle** [comment]
These images have been run through like 8 image optimizers at this point, I don't understand how they keep getting smaller

**Comment by Daniel15** [comment]
We need to continue optimizing them until there's just a single byte left. That's how it works, right? 😆 

It looks like ImageAlpha has some sort of lossy compression algorithms (https://pngmini.com/lossypng.html), the previous optimizers we've used were probably all lossless.

**Pull request merged**
