### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

\assets\posts\2016-11-24-offline-mirror\yarn-offline-blog-releases.png (31.09%))
\assets\posts\2016-11-24-offline-mirror\yarn-offline-blog-offline-mirror-list.png (17.1%))
\assets\posts\2016-11-24-offline-mirror\yarn-offline-blog-offline-mirror-size.png (28.07%))

### CODE REVIEW

**Comment by Daniel15** [comment]
Neat. Thanks @dabutvin @ImgBotApp

**Comment by Haroenv** [comment]
Deploy preview ready!

Built with commit f9f5f46f0f1cf8dbd8e052c437d83835d550d2f6

https://deploy-preview-620--yarnpkg.netlify.com

**Comment by Daniel15** [comment]
Confirmed it still looks good on the site: https://deploy-preview-620--yarnpkg.netlify.com/blog/2016/11/24/offline-mirror/

**Comment by dabutvin** [comment]
👍 happy to help

If you want more prs from ImgBot here, or any of your other projects, feel free to install the GitHub app.

https://github.com/apps/ImgBot

**Pull request merged**
