### PR TITLE
Fix _featurettes.scss

### PR DESCRIPTION
**Pull request by twirlfog**
changed to
.featurette height: 100%;
.featurette margin-bottom: 1rem;
to include all content

### CODE REVIEW

**Comment by Haroenv** [comment]
Hi! How can I check what this fixed?

**Comment by twirlfog** [comment]
Hi ! I have attached screenshots for clarity.
Before:
[image: before.jpg]
________________________________________________________________________
After:
[image: after.jpg]

чт, 23 мая 2019 г. в 10:48, Haroen Viaene <notifications@github.com>:

**Comment by Haroenv** [comment]
Hi, looks like your email stripped your images out, I just see "[image: before.jpg]`

**Comment by Haroenv** [comment]
Thanks for your contribution, but it seems like this breaks the text for English :/

**Comment by twirlfog** [comment]
Before:
featurelette before fix

After:
featurelette after fix

Other problems with this fix in the rest of the site are not noticed

**Comment by twirlfog** [comment]
> 
> 
> Thanks for your contribution, but it seems like this breaks the text for English :/
fix after en

where and in what browser problems ?
I have all is displayed normally

**Comment by Haroenv** [comment]
if you go on a medium size, 
Screenshot 2019-05-23 at 13 33 31

before this was:

Screenshot 2019-05-23 at 13 33 52

**Comment by twirlfog** [comment]
Yes need a fixed block size.

**Pull request closed without merging**
