### PR TITLE
fix(normalize): drop . and .. reliably

### PR DESCRIPTION
**Pull request by Haroenv**

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview failed.

Built with commit 236864d0949b8e02c31e77953341b16b19140b43

https://app.netlify.com/sites/yarnpkg/deploys/59b175990752d047aa4568da

**Comment by Haroenv** [comment]
Deploy preview failed.

Built with commit 191fd41a533d7632e86b263d4b45928e60aad0d9

https://app.netlify.com/sites/yarnpkg/deploys/59b1763e424ef23b6e3a27b7

**Comment by Haroenv** [comment]
Deploy preview failed.

Built with commit 29da8913ab260e8df09c9c8fd017d5217b34d2fb

https://app.netlify.com/sites/yarnpkg/deploys/59b177480752d05aaec40576

**Comment by Daniel15** [comment]
Thank you! 😃

**Pull request merged**
